import { PageSchema } from "@/components/constructor/page-render/types";
import {
    COMPANY_ADDRESS,
    COMPANY_EMAIL,
    COMPANY_LEGAL_NAME,
    COMPANY_NUMBER,
    COMPANY_PHONE,
} from "@/resources/constants";

const refundPolicySchema: PageSchema = {
    meta: {
        title: "Refund & Return Policy – ResilePlans",
        description:
            "Official Refund & Return Policy for ResilePlans: refunds for tokens, digital outputs, services, disputes, and consumer rights.",
        keywords: [
            "refund policy",
            "return policy",
            "resileplans",
            "tokens",
            "business plan",
            "digital content",
            "consumer rights",
            "investor pack",
        ],
        canonical: "/refund-policy",
        ogImage: {
            title: "ResilePlans – Refund & Return Policy",
            description:
                "Transparent refund and return policy for ResilePlans business planning platform.",
            bg: "#ffffff",
            color: "#000000",
        },
    },
    blocks: [
        {
            type: "text",
            title: "Refund & Return Policy",
            bullets: [
                "Effective date: 20 January 2026",
            ],
        },
        {
            type: "text",
            title: "1. Summary",
            bullets: [
                "1.1. Request Handling: All refund requests are processed under this Policy and applicable UK consumer law, specifically taking into account the digital and bespoke nature of our services.",
                "1.2. Processing Time: Typically 5–10 business days after approval (banking timelines may vary).",
                "1.3. Token Usage: Tokens typically function as a non-refundable prepayment. Once Tokens are consumed to generate a Business Plan, Investor Pack, or to initiate a Custom Plan consultation, they cannot be refunded.",
                "1.4. Digital Nature: The Service provides digital files (PDF, DOCX, XLS) and intellectual property. There are no physical items to ship or return.",
                "1.5. Result Disclaimer: We do not offer refunds based on the outcome of your business endeavors (e.g., failure to secure a loan, grant, or investment) or personal preference regarding the writing style.",
                `1.6. Contact: To submit a request, email ${COMPANY_EMAIL} with your Order Reference.`,
                "1.7. Exchange Rate: Reference rate for Tokens is approximately 100 Tokens = £1.00 / €1.17 / $1.29.",
            ],
        },
        {
            type: "text",
            title: "2. Scope and Legal Notice",
            bullets: [
                "2.1. This Refund & Return Policy (“Policy”) governs all cancellations, disputes, and refund requests for purchases made via resileplans.co.uk, including Wallet top-ups (Token purchases) and orders for AI Instant Plans, Investor Packs, and Custom Plans.",
                `2.2. The Service is operated by ${COMPANY_LEGAL_NAME} (Company Number ${COMPANY_NUMBER}), registered at ${COMPANY_ADDRESS} (“ResilePlans”, “we”, “us”, “our”).`,
                "2.3. Nothing in this Policy is intended to limit your statutory rights under UK law (including the Consumer Rights Act 2015 and Consumer Contracts Regulations 2013), except where distinct exemptions for digital content and bespoke goods apply.",
            ],
        },
        {
            type: "text",
            title: "3. Key Definitions",
            bullets: [
                "3.1. Wallet / Tokens: The digital credit balance in your Account. Tokens are a prepayment mechanism and are not electronic money or a savings account.",
                "3.2. Deliverables / Outputs: Any Business Plans, Pitch Decks, Financial Models, market research, or spreadsheets generated by our AI or prepared by our specialists based on your input.",
                "3.3. Service Type – Instant Service: AI-generated plans delivered immediately.",
                "3.4. Service Type – Bespoke Service: Custom Plans involving human analysis and manual drafting.",
                "3.5. Order: A confirmed purchase of Tokens or specific Service package.",
            ],
        },
        {
            type: "text",
            title: "4. General Refund Principles",
            bullets: [
                '4.1. The "No Return" Nature of Digital Data. By purchasing Tokens and clicking "Generate", "Order", or "Start Project", you expressly consent to the immediate performance of the contract. You acknowledge that once the digital content is made available (for AI plans) or the work has commenced (for Custom plans), you lose your right of withdrawal (the 14-day cooling-off period).',
                "4.2. Refund Cap. Any refund granted is strictly limited to the amount paid for the specific Transaction. We are not liable for any third-party fees (e.g., bank overdraft fees) or currency exchange losses.",
                "4.3. Accuracy of Client Input. Our Deliverables are created based on the data you provide (business idea, financial assumptions, market sector). If your input is incomplete, unrealistic, or incorrect, the resulting Business Plan may be suboptimal. Re-generating the plan with new data requires new Tokens and is not grounds for a free revision or refund.",
                "4.4. Subjectivity & Investment Results. ResilePlans provides documentation tools, not guaranteed funding.",
                "4.5. A refund will not be issued if you do not like the tone, formatting, or vocabulary of the AI-generated text.",
                "4.6. A refund will not be issued if an investor, bank, or grant authority rejects your application.",
                "4.7. A refund will not be issued if you decide to abandon the business idea after the document has been created.",
            ],
        },
        {
            type: "text",
            title: "5. Wallet Top-ups (Token Purchases)",
            bullets: [
                "5.1. Prepayment Only. Tokens are sold as bundles (e.g., 900 Tokens for the AI Plan, 5000 Tokens for the Investor Pack). Unused Tokens are generally non-refundable and cannot be exchanged for cash.",
                '5.2. Exceptional Refunds. In rare cases (e.g., accidental duplicate payment or technical billing error), we may refund a Token top-up if the Tokens have not yet been used. Once a Token is used (even partially), the bundle is considered "opened" and non-refundable.',
                "5.3. Expiry. While Tokens do not currently expire, we reserve the right to close inactive accounts after 24 months.",
            ],
        },
        {
            type: "text",
            title: "6. Cancellations of Specific Services",
            bullets: [
                "6.1. AI Instant Plans & Investor Packs (Automated). These services are fulfilled instantly. Once you click the button to generate the documents, the Tokens are consumed immediately. No cancellation or refund is possible after generation.",
                "6.2. Custom Plans (Bespoke/Consultancy). Custom Plans involve manual work tailored to your specific business requirements. Under UK law, goods or services made to the consumer's specifications are exempt from standard cancellation rights.",
                "6.3. Before Work Begins: If you cancel before a specialist has started working on your project, we may, at our discretion, refund the Tokens.",
                "6.4. Work In Progress: Once research or drafting has begun, no full refund is available. A partial refund may be considered strictly based on the percentage of work not yet completed, minus a 20% administration fee.",
                "6.5. Completed Drafts: Once a draft has been delivered for your review, the service is considered fully rendered.",
            ],
        },
        {
            type: "text",
            title: "7. Quality Issues & Technical Faults",
            bullets: [
                "7.1. Technical Defects. If a Deliverable is technically defective (e.g., the file is corrupted, blank, or the financial formulas are broken due to a system error), you must notify us within 7 days.",
                "7.2. In such a case, we will repair the file.",
                "7.3. In such a case, we may re-run the generation at no cost.",
                "7.4. In such a case, we may credit your Wallet with the Tokens used.",
                "7.5. Refunds to the bank card are only issued if we are unable to rectify the technical fault.",
                `7.6. "As Is" Content. AI-generated content is provided "as is". Minor factual hallucinations or generic phrasing inherent to Large Language Models (LLMs) are not considered "defects" eligible for a refund. You are expected to edit the final output.`,
            ],
        },
        {
            type: "text",
            title: "8. How to Request a Refund",
            bullets: [
                `8.1. To raise a claim, please email ${COMPANY_EMAIL} with the subject line "Refund Request".`,
                "8.2. You must include your Order ID and the email address used for the account.",
                '8.3. You must include a description of the issue (e.g., "File corrupted", "Duplicate charge").',
                "8.4. You must include evidence (Screenshots of the error, bank statement for double charge).",
                "8.5. We aim to acknowledge receipt within 48 hours.",
                "8.6. We will investigate and provide a final decision within 5 business days.",
                "8.7. Approved refunds are processed within 5–10 business days (funds may take longer to appear on your statement depending on your bank).",
            ],
        },
        {
            type: "text",
            title: "9. Chargebacks & Disputes",
            bullets: [
                '9.1. Friendly Fraud. If you initiate a chargeback with your bank for a validly delivered Service (e.g., claiming "Service not received" after downloading a Business Plan), we classify this as "Friendly Fraud".',
                "9.2. In the event of an unjustified chargeback, your Account will be permanently suspended.",
                "9.3. In the event of an unjustified chargeback, we will dispute the chargeback providing full logs of your IP address, download history, and Token usage.",
                "9.4. In the event of an unjustified chargeback, we reserve the right to pursue the debt via collection agencies.",
                "9.5. We strongly encourage you to contact our support team before contacting your bank. We are often able to resolve issues (e.g., by providing extra Tokens) faster than the banking dispute process.",
            ],
        },
        {
            type: "text",
            title: "10. Taxes",
            bullets: [
                "10.1. Prices are inclusive of applicable VAT unless stated otherwise for B2B clients.",
                "10.2. If a refund is issued, we will refund the tax amount only if we are able to reclaim it from the tax authorities or if required by law.",
            ],
        },
        {
            type: "text",
            title: "11. Data Protection",
            bullets: [
                "11.1. To process refunds and handle disputes, we may retain transaction data (including Order IDs, partial card details, and activity logs) for up to 6 years in compliance with UK tax and accounting laws.",
                "11.2. This processing is conducted in accordance with our Privacy Policy.",
            ],
        },
        {
            type: "text",
            title: "12. Illustrative Examples",
            bullets: [
                "12.1. Scenario A (No Refund): You bought the Investor Pack (5000 Tokens), generated the documents, but later realized you needed a different business model.",
                "12.2. Scenario A Result: Tokens are consumed. No refund. You must purchase new Tokens for a new plan.",
                "12.3. Scenario B (Refund Approved): You tried to buy 900 Tokens (£9.00) but the website froze, and you were charged twice on your Visa card.",
                "12.4. Scenario B Result: We will refund the duplicate transaction in full.",
                "12.5. Scenario C (Partial/No Refund): You ordered a Custom Plan, our expert spent 3 days writing it, and sent you the draft. You decide you no longer want to start the business.",
                "12.6. Scenario C Result: The service has been performed. No refund is due.",
            ],
        },
        {
            type: "text",
            title: "13. Contact Details",
            bullets: [
                COMPANY_LEGAL_NAME || "",
                `Registered Office: ${COMPANY_ADDRESS || ""}`,
                `Company Number: ${COMPANY_NUMBER || ""}`,
                `Email: ${COMPANY_EMAIL || ""}`,
                `Phone: ${COMPANY_PHONE || ""}`,
                "Accepted Payments: Visa, MasterCard",
                "Currencies: GBP (£), EUR (€), USD ($)",
            ],
        },
    ],
};

export default refundPolicySchema;